"""add_school_id

Revision ID: 1a8dbd4db6d0
Revises: f392dbe028ca
Create Date: 2023-05-03 14:44:15.421539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8dbd4db6d0'
down_revision = 'f392dbe028ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons_hotfix', sa.Column('school_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons_hotfix', 'school_id')
    # ### end Alembic commands ###
