"""lesson hotfix

Revision ID: 3256e9b567f5
Revises: 086e3bccd639
Create Date: 2023-04-29 20:02:42.108296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3256e9b567f5'
down_revision = '086e3bccd639'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons_hotfix',
    sa.Column('hotfix_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('is_existing', sa.Boolean(), nullable=True),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name=op.f('fk_lessons_hotfix_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_lessons_hotfix_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotfix_id', name=op.f('pk_lessons_hotfix'))
    )
    op.create_index(op.f('ix_lessons_hotfix_hotfix_id'), 'lessons_hotfix', ['hotfix_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_hotfix_hotfix_id'), table_name='lessons_hotfix')
    op.drop_table('lessons_hotfix')
    # ### end Alembic commands ###
