"""Add info for user

Revision ID: b6ae9a29d1aa
Revises: 1a8dbd4db6d0
Create Date: 2023-05-04 15:55:55.779017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ae9a29d1aa'
down_revision = '1a8dbd4db6d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_teacher_id_teachers'), 'users', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_users_class_id_classes'), 'users', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_class_id_classes'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_teacher_id_teachers'), 'users', type_='foreignkey')
    op.drop_column('users', 'teacher_id')
    op.drop_column('users', 'class_id')
    # ### end Alembic commands ###
