"""lesson id nullable

Revision ID: f392dbe028ca
Revises: 3256e9b567f5
Create Date: 2023-04-30 09:00:57.036819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f392dbe028ca'
down_revision = '3256e9b567f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons_hotfix', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons_hotfix', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
